# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('dep', 'Deposit'), ('wdl', 'Withdrawal')], default='dep', max_length=2),
        ),
    ]
