# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_transaction_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
    ]
